config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  get 'logic' => 'logic#index'
  get 'number_systems' => 'number_systems#index'
  get 'search_efficiency' => 'search_efficiency#index'
  get 'sets' => 'sets#index'
  get 'hashing' => 'hashing#index'
  get 'tree' => 'tree#index'
  get 'probability' => 'probability#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/concerns/number_systems.rb
module NumberSystems
  BITS_DISPLAY = ['0', '1']
  BASE_DISPLAY = ('0'..'9').to_a + ('A'..'F').to_a
  BASE_TO_N = BASE_DISPLAY.map.with_index{ |base_n, n| [base_n, n] }.reduce({}) do |hash, pair|
    hash[pair[0]] = pair[1]
    hash
  end

  def NumberSystems.n_to_bit(n, leading_zeros = 4)
    output = ''
    until n == 0
      bit = n % 2
      output = BITS_DISPLAY[bit] + output
      n /= 2
    end
    output.rjust(leading_zeros, '0')
  end

  def NumberSystems.n_to_base(n:, base:, min_length: 1)
    output = ''
    until n == 0
      bit = n % base
      output = BASE_DISPLAY[bit] + output
      n /= base
    end
    output.rjust(min_length, '0')
  end

  def NumberSystems.base_to_n(n_string:, base:)
    n_string.chars.reverse.map.with_index{ |c, offset| BASE_TO_N[c] * base ** offset }.reduce(:+)
  end

  def NumberSystems.create_table(base: 2, row_count: 16, min_length: 4)
    rows = []
    row_count.times do |a|
      row = []
      base.times do |b|
        #row << n_to_bit(a * base + b)
        n = a * base + b
        row << {
          n: n,
          text: n_to_base(n: n, base: base, min_length: min_length)
        }
      end
      rows << row
    end
    rows
  end
end

app/controllers/number_systems_controller.rb
class NumberSystemsController < ApplicationController
  def index
    @active_n = params[:n].to_i
    @base2_rows = NumberSystems.create_table(base: 2, row_count: 20)
    @base8_rows = NumberSystems.create_table(base: 8, row_count: 20)
    @base10_rows = NumberSystems.create_table(base: 10, row_count: 20)
    @base16_rows = NumberSystems.create_table(base: 16, row_count: 20)
  end
end

app/helpers/number_systems_helper.rb
module NumberSystemsHelper
end

app/views/number_systems/_expanded.html.erb
<%= NumberSystems.n_to_base(n: n, base: base).chars.reverse.map.with_index do |bit, offset| %>
  <% "<strong>#{ bit }</strong> ✕ #{ base }<sup>#{ offset }</sup>" %>
<% end.reverse.join(' + ').html_safe %>

app/views/number_systems/_table.html.erb
<% active_n = local_assigns[:active_n] # Optional %>

<h2><%= title %></h2>
<article>
<% rows.each do |row| %>
  <div>
  <% row.each do |item| %>
    <%= content_tag (item[:n] == active_n ? :strong : :span) do %>
      <code><%= link_to item[:text], number_systems_path(n: item[:n]) %></code>
    <% end %>
  <% end %>
  </div>
<% end %>
</article>

app/views/number_systems/index.html.erb
<h1>Number Systems</h1>

<%= form_with(method: :get) do |f| %>
  <%= f.label :n, 'Selected number (base 10)' %>
  <%= f.text_field :n, value: @active_n %>  
<% end %>

<dl>
  <dt>Base 2:</dt>
  <dd><%= render 'expanded', n: @active_n, base: 2 %></dd>

  <dt>Base 8:</dt>
  <dd><%= render 'expanded', n: @active_n, base: 8 %></dd>

  <dt>Base 10:</dt>
  <dd><%= render 'expanded', n: @active_n, base: 10 %></dd>

  <dt>Base 16:</dt>
  <dd><%= render 'expanded', n: @active_n, base: 16 %></dd>
</dl>

<%= render 'table', rows: @base2_rows, title: 'Base 2 (binary)', active_n: @active_n %>
<%= render 'table', rows: @base8_rows, title: 'Base 8 (octal)', active_n: @active_n %>
<%= render 'table', rows: @base10_rows, title: 'Base 10 (decimal)', active_n: @active_n %>
<%= render 'table', rows: @base16_rows, title: 'Base 16 (hexdecimal)', active_n: @active_n %>