config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  get 'logic' => 'logic#index'
  get 'number_systems' => 'number_systems#index'
  get 'search_efficiency' => 'search_efficiency#index'
  get 'sets' => 'sets#index'
  get 'hashing' => 'hashing#index'
  get 'tree' => 'tree#index'
  get 'probability' => 'probability#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_efficiency_controller.rb
require_relative './concerns/string_hashing'

class SearchEfficiencyController < ApplicationController
  ITEMS_ARRAY = %Q(
Deer
Goat
Jaguar
Panther
Chicken
Salamander
Dog
Civet
Lemur
Ermine
Bear
Lizard
Hamster
Guanaco
Hippopotamus
Capybara
Ground hog
Mule
Octopus
Bumble bee
).lines.map(&:strip).select(&:present?)

  def index
    @query = params.fetch(:q, '')
    @step = @query.present? ? params.fetch(:step, '0').to_i : 0
    @items = ITEMS_ARRAY
    @items_sorted = ITEMS_ARRAY.sort

    # Binary search
    low = 0
    high = @items_sorted.length
    @binary_search_step_result = []
    @step.times do
      mid = low + ((high - low) / 2)
      @binary_search_step_result << mid
      direction = @items_sorted[mid] <=> @query
      if direction == 0
        break
      elsif direction < 0
        low = mid + 1
      else # direction > 0
        high = mid
      end
    end

    @b = BinarySearchTree.new
    ITEMS_ARRAY.each do |item|
      @b.insert item, item
    end

    @binary_tree_step_nodes = []
    @binary_tree_search_steps = []
    # @binary_tree_found_node = @b.find(@query)
    # node = @binary_tree_found_node
    # while node
    #   @binary_tree_step_nodes << node
    #   node = node.parent
    # end
    # @binary_tree_step_nodes.reverse!

    node = @b.root
    #while node.present?
    @step.times do
      break if node.nil?
      @binary_tree_step_nodes << node
      case @query <=> node.key
      when -1
        @binary_tree_search_steps << -1
        node = node.left
      when 1
        @binary_tree_search_steps << 1
        node = node.right
      else
        @binary_tree_search_steps << 0
        node = nil
      end
    end

    @hash_size = 31
    @items_hash_array = Array.new(@hash_size) { [] }
    ITEMS_ARRAY.each do |item|
      hash_value = item.djb2_hash 
      @items_hash_array[hash_value % @hash_size] << item
    end

    if @step >= 1
      @items_hash_found_offset = @query.djb2_hash % @hash_size
    end
  end
end

app/helpers/search_efficiency_helper.rb
module SearchEfficiencyHelper
end

app/views/search_efficiency/_linear.html.erb
<ol class="neutral">
<% items.each_with_index do |item, index| %>
  <li>
    <% checked = index < step %>
    <% found = checked && (item == query) %>
    <% current = index+1 == step %>
    <% class_name = (checked ? (found ? 'positive' : 'negative') : nil) %>
    <%= content_tag (current ? :strong : :span), item, class: class_name %>
    <% if found %>
      <%= pluralize(index + 1 + extra, 'step') %>
    <% end %>
  </li>
<% end %>
</ol>

app/views/search_efficiency/index.html.erb
<h1>Search Efficiency</h1>

<% if @query.present? %>
  <nav>
    <strong>“<%= @query %>”</strong>
    <%= @step %>
    <%= link_to 'Next', search_efficiency_path(step: @step + 1, q: @query) %>
    <%= link_to 'Restart', search_efficiency_path(q: @query) %>
  <nav>
<% end %>
<nav>
  Search for:
  <%= link_to 'Lemur', search_efficiency_path(q: 'Lemur') %>
  <%= link_to 'Salamander', search_efficiency_path(q: 'Salamander') %>
  <%= link_to 'Hippopotamus', search_efficiency_path(q: 'Hippopotamus') %>
  <%= link_to 'Goat', search_efficiency_path(q: 'Goat') %>
<nav>

<h2>Linear Search — searching an array</h2>

<%= render 'linear', items: @items, step: @step, query: @query, extra: 0 %>

<h2>Binary Search — searching a sorted array</h2>
<ol>
<% @items_sorted.each_with_index do |item, index| %>
  <li>
    <% checked = @binary_search_step_result.include?(index) %>
    <% found = checked && (item == @query) %>
    <% current = @binary_search_step_result.last == index %>
    <% class_name = (checked ? (found ? 'positive' : 'negative') : nil) %>
    <%= content_tag (current ? :strong : :span), item, class: class_name %>
    <% if found %>
      <%= pluralize(@binary_search_step_result.length, 'step') %>
    <% end %>
  </li>
<% end %>
</ol>

<h2>Binary Search Tree — searching a balanced tree</h2>

<%= render 'tree/node', node: @b.root, search_steps: @binary_tree_search_steps %>

<h2>Hashed values — searching a Hash/Dictionary</h2>

<ol>
<% @items_hash_array.each_with_index do |values, hash_offset| %>
  <% found_bucket = hash_offset == @items_hash_found_offset %>
  <% class_name = (found_bucket ? 'positive' : nil) %>
  <%= content_tag :li, class: class_name do %>
    <%= render 'linear', items: values, step: found_bucket ? @step - 1 : 0, extra: 1, query: @query %>
  <% end %>
<% end %>
</ol>